version: '3.7'
services:
  back:
    container_name: 'xmas_back'
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  front:
    container_name: 'xmas_front'
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - ./backend/static:/app/public/back:ro